#!/usr/bin/env python3
"""PreToolUse hook: block edits to the generated docs/content.js.

content.js is produced by scripts/build_site.py from AI-PM-Handbook.md, so any
hand-edit is silently overwritten on the next build. Exit code 2 blocks the
tool call and feeds the reason back to Claude.
"""
import json
import sys


def main():
    try:
        payload = json.load(sys.stdin)
    except Exception:
        return 0  # malformed payload — don't block

    tool_input = payload.get("tool_input") or {}
    file_path = (tool_input.get("file_path") or "").replace("\\", "/")
    if file_path.endswith("docs/content.js"):
        sys.stderr.write(
            "Blocked: docs/content.js is generated by scripts/build_site.py. "
            "Edit AI-PM-Handbook.md instead and the site rebuilds automatically.\n")
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
